- name: install the WebDAV Redirector
  ansible.windows.win_feature:
    name: WebDAV-Redirector
  register: reboot_webdav

- name: reboot if the WebDAV Redirector has just been installed
  win_reboot:
  when: reboot_webdav.changed

- name: enable the WebClient service
  ansible.windows.win_powershell:
    script: |
      net start webclient