ansible_user: vagrant
ansible_password: vagrant
ansible_connection: winrm
ansible_port: 5986
ansible_winrm_server_cert_validation: ignore
ansible_winrm_operation_timeout_sec: 400
ansible_winrm_read_timeout_sec: 500