- name: remove the Anonymous Logon special group from the Pre-Windows 2000 Compatible Access group
  ansible.windows.win_powershell:
    script: |
      net localgroup "Pre-Windows 2000 Compatible Access" "NT AUTHORITY\Anonymous Logon" /delete