- name: Local administrator's password
  hosts: all
  vars_files:
    - ../../vars/breakingbad.json
  roles:
    - role: ../../roles/base_build/01-hosts/local_administrator_password
  tags:
    - local_administrator_password
  gather_facts: false

- name: Windows updates
  hosts: all
  roles:
    - role: ../../roles/base_build/01-hosts/windows_updates_off
  gather_facts: false

- name: Resolve NIC teaming issues (via address registration)
  hosts: dc01
  roles:
    - role: ../../roles/base_build/01-hosts/address_registration
  tags:
    - address_registration
  gather_facts: false

- name: Resolve NIC teaming issues (via interface metrics)
  hosts: srv01, srv02
  roles:
    - role: ../../roles/base_build/01-hosts/interface_metrics
  tags:
    - interface_metrics
  gather_facts: false