- name: Domain creation
  hosts: dc01
  vars_files:
    - ../../vars/breakingbad.json
  roles:
    - role: ../../roles/base_build/02-adds/domain
  tags:
    - domain_creation
  gather_facts: false

- name: DNS forwarder
  hosts: dc01
  roles:
    - role: ../../roles/base_build/02-adds/dns
  tags:
    - dns_forwarder
  gather_facts: false

- name: Resolve NIC teaming issues (via DNS client requests)
  hosts: dc01
  roles:
    - role: ../../roles/base_build/02-adds/dns_client_requests
  tags:
    - dns_client_requests
  gather_facts: false

- name: Organizational units, groups, computers and users
  hosts: dc01
  vars_files:
    - ../../vars/breakingbad.json
  roles: 
    - role: ../../roles/base_build/02-adds/ou_groups_computers_users
  tags:
    - ou_groups_computers_users
  gather_facts: false

- name: Domain membership
  hosts: srv01, srv02
  vars_files:
    - ../../vars/breakingbad.json
  roles:
    - role: ../../roles/base_build/02-adds/domain_membership
  tags:
    - domain_membership
  gather_facts: false