- name: disable Kerberos Pre-Authentication for a user
  ansible.windows.win_shell:
    Get-ADUser -Identity "{{ user }}" | Set-ADAccountControl -DoesNotRequirePreAuth:$true
  vars:
    user: user_name