- name: ADCS web enrollement
  hosts: dc01
  vars:
    action: "{{ action }}" # taken from the --extra-vars cli option
  roles:
    - role: ../../roles/vulnerabilities/01/enable
      when: action == 'enable'
    - role: ../../roles/vulnerabilities/01/disable
      when: action == 'disable'
  gather_facts: false