- name: NTLMv1
  hosts: "{{ host_name | default('srv01', true) }}" # extra-vars
  vars:
    action: "{{ action }}" # extra-vars

  roles:
    - role: ../../roles/vulnerabilities/02/enable
      when: action == "enable"

    - role: ../../roles/vulnerabilities/02/disable
      when: action == "disable"   
  gather_facts: false