- name: WebClient
  hosts: "{{ host_name | default('srv02') }}" # extra-vars
  vars:
    action: "{{ action }}" # extra-vars

  roles:
    - role: ../../roles/vulnerabilities/03/enable
      when: action == "enable"

    - role: ../../roles/vulnerabilities/03/disable
      when: action == "disable"
  gather_facts: false