- name: IPv6 poisoning
  hosts: "{{ host_name | default('srv02', true) }}" # extra-vars
  vars:
    action: "{{ action }}" # extra-vars
    
  roles:
    - role: ../../roles/vulnerabilities/05/enable
      when: action == "enable"

    - role: ../../roles/vulnerabilities/05/disable
      when: action == "disable"

    - role: ../../roles/vulnerabilities/05/trigger
      when: action == "trigger"
  gather_facts: false