- name: LLMNR, NBT-NS & mDNS poisoning
  hosts: "{{ host_name | default('srv02', true) }}" # taken from the --extra-vars cli option
  vars:
    action: "{{ action }}" # taken from the --extra-vars cli option
  vars_files:
    - ../../vars/breakingbad.json
  roles:
    - role: ../../roles/vulnerabilities/06/enable
      when: action == 'enable'
    - role: ../../roles/vulnerabilities/06/disable
      when: action == 'disable'
    - role: ../../roles/vulnerabilities/06/trigger
      when: action == 'trigger'
      user: "{{ user_name | default('walter.white', true) }}" # taken from the --extra-vars cli option
      share: "{{ share_name | default('made-by-walter-white', true) }}" # taken from the --extra-vars cli option
  gather_facts: false