- name: Password in user's description
  hosts: dc01
  vars:
    action: "{{ action }}" # extra-vars
  vars_files:
    - ../../vars/breakingbad.json

  roles:
    - role: ../../roles/vulnerabilities/07/enable
      when: action == "enable"
      user: "{{ user_name | default('saul.goodman', true) }}" # extra-vars

    - role: ../../roles/vulnerabilities/07/disable
      when: action == "disable"
      user: "{{ user_name | default('saul.goodman', true) }}" # extra-vars
  gather_facts: false