- name: Kerberos Pre-Authentication flag
  hosts: dc01
  vars:
    action: "{{ action }}" # extra-vars
  vars_files:
    - ../../vars/breakingbad.json

  roles:
    - role: ../../roles/vulnerabilities/09/enable
      when: action == 'enable'
      user: "{{ user_name | default('jessie.pinkman', true) }}" # extra-vars

    - role: ../../roles/vulnerabilities/09/disable
      when: action == 'disable'
      user: "{{ user_name | default('jessie.pinkman', true) }}" # extra-vars
  gather_facts: false