- name: ESC1
  hosts: dc01
  vars:
    action: "{{ action }}" # extra-vars
  vars_files:
    - ../../vars/breakingbad.json

  roles:
    - role: ../../roles/vulnerabilities/10/enable
      when: action == 'enable'

    - role: ../../roles/vulnerabilities/10/disable
      when: action == 'disable'
  gather_facts: false