- name: set the dns IP to the IP of the domain controller (dc01)
  win_dns_client:
    adapter_names: "Ethernet 2"
    dns_servers:
    - "{{ hostvars['dc01']['host_ip'] }}"

- name: install File-Services and FS-FileServer
  win_feature:
    name: File-Services, FS-FileServer
    state: present
    include_management_tools: True

- name: add entity to a domain
  win_domain_membership:
    dns_domain_name: "{{ domain.domain_fqdn }}"
    domain_admin_user: "{{ domain.administrator_name}}@{{ domain.domain_fqdn }}"
    domain_admin_password: "{{ domain.administrator_password }}"
    state: domain
  register: reboot_domain_membership

- name: reboot if needed
  win_reboot:
  when: reboot_domain_membership.reboot_required