- name: change the Admininistrator account's password
  win_user:
    name: Administrator
    password: "{{ password }}"
    password_never_expires: yes
  vars:
    query_local_administrator_password: "computers[?name=='{{ host_name }}'].local_administrator_password | [0]" # query for the variable "password"
    password: "{{ domain | json_query(query_local_administrator_password) }}"