- name: disable the registration of the Ethernet interface (NAT address) in DNS
  ansible.windows.win_shell: |
    Get-NetAdapter Ethernet | Set-DNSClient -RegisterThisConnectionsAddress $False

- name: prioritize the Ethernet 2 interface (local) as the default for routing
  ansible.windows.win_shell: |
    Set-NetIPInterface -InterfaceAlias "Ethernet 2" -InterfaceMetric 10