- name: create a GPO, link it to an OU and set permissions for a specific target
  ansible.windows.win_shell: |
    New-GPO -Name "{{ gpo }}"
    New-GPLink -Name "{{ gpo }}" -Target "{{ oupath }}"
    Set-GPPermissions -Name "{{ gpo }}" -PermissionLevel "{{ permissionlevel }}" -TargetName "{{ targetname }}" -TargetType "{{ targettype }}"
  vars:
    query_path: "organizational_units[?name=='{{ ou }}'].path | [0]" # query for the variable "oupath"
    oupath: "{{ domain | json_query(query_path) }}"
    query_local_administrator_password: "computers[?name=='{{ host_name }}'].local_administrator_password | [0]" # query for the variable "password"
    password: "{{ domain | json_query(query_local_administrator_password) }}"
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: Administrator
    ansible_become_password: "{{ password }}"