- name: remove the Los Pollos Hermanos GPO
  ansible.windows.win_powershell:
    script: |
      Remove-GPO -Name "Los Pollos Hermanos"

- name: move srv01 to the Computers container
  win_domain_computer:
    name: srv01
    dns_hostname: srv01.breakingbad.local
    ou: CN=Computers,DC=breakingbad,DC=local

- name: remove the Gustavo Fring user
  win_domain_user:
    name: gustavo.fring
    state: absent