- name: install ADCS role
  win_feature:
    name: AD-Certificate
    state: present
    include_sub_features: yes
    include_management_tools: yes
  register: win_features

- name: install Cert Authority role
  win_feature:
    name: ADCS-Cert-Authority
    state: present
    include_management_tools: yes

- name: install Web Enrollment role
  win_feature:
    name: ADCS-Web-Enrollment
    state: present

- name: install Certification Authority role
  ansible.windows.win_powershell:
    script: |
      $AdministratorPassword = ConvertTo-SecureString "{{ domain_password }}" -AsPlainText -Force
      $PSCredential = New-Object System.Management.Automation.PSCredential ("{{ domain_username }}", $AdministratorPassword)
      Install-AdcsCertificationAuthority -Credential $PSCredential -CAType EnterpriseRootCA -CryptoProviderName "RSA#Microsoft Software Key Storage Provider" -KeyLength 2048 -HashAlgorithmName SHA256 -ValidityPeriod Years -ValidityPeriodUnits 5 -CACommonName "{{ ca_common_name }}" -Force
  vars:
    domain_username: "{{ domain.administrator_name }}"
    domain_password: "{{ domain.administrator_password }}"
    ca_common_name: "{{ domain.ca_name }}"