- name: create a domain
  win_domain:
    domain_netbios_name: "{{ domain.domain_netbios_name }}"
    dns_domain_name: "{{ domain.domain_fqdn }}"
    safe_mode_password: "{{ domain.administrator_password }}"
  register: reboot_domain

- name: reboot if needed
  win_reboot:
    reboot_timeout: 900
    post_reboot_delay: 100
  when: reboot_domain.changed

- name: ensure that the host is configured as a domain controller
  win_domain_controller:
    dns_domain_name: "{{ domain.domain_fqdn }}"
    domain_admin_user: "{{ domain.administrator_password }}@{{ domain }}"
    domain_admin_password: "{{ domain.administrator_password }}"
    safe_mode_password: "{{ domain.administrator_password }}"
    state: domain_controller