- name: create a domain
  win_domain:
    domain_netbios_name: "{{ domain.domain_netbios_name }}"
    dns_domain_name: "{{ domain.domain_fqdn }}"
    safe_mode_password: "{{ domain.administrator_password }}"
  register: reboot_domain

- name: reboot if a domain was created
  win_reboot:
    reboot_timeout: 900
    post_reboot_delay: 100
  when: reboot_domain.changed