- name: change the computer host name
  win_hostname:
    name: "{{ host_name }}"
  register: win_hostname

- name: reboot if needed
  win_reboot:
    reboot_timeout: 600
    post_reboot_delay: 30
  when: win_hostname.reboot_required