- name: create organization units (OU)
  community.windows.win_domain_ou:
    name: "{{ item.name }}"
    path: "{{ item.path }}"
  loop: "{{ domain.organizational_units }}"

# - name: create organizational units (OU)
#   ansible.windows.win_powershell:
#     script: |
#       [CmdletBinding()]
#       param (
#         [String]
#         $Name,

#         [String]
#         $Path
#       )

#       New-ADOrganizationalUnit -Name $Name -Path $Path
#     error_action: silently_continue
#     parameters:
#       Name: "{{ item.name }}"
#       Path: "{{ item.path }}"
#   loop: "{{ domain.organizational_units }}"

- name: create groups
  win_domain_group:
    scope: "{{ item.scope }}"
    name: "{{ item.name }}"
    path: "{{ item.path }}"
  loop: "{{ domain.groups }}"

- name: create users
  win_domain_user:
    password_never_expires: yes
    name: "{{ item.name }}"
    firstname: "{{ item.firstname }}"
    lastname: "{{ item.lastname }}"
    password: "{{ item.password }}"
    path: "{{ item.path }}"
    # domain_username: "{{ domain.administrator_name}}"
    # domain_password: "{{ domain.administrator_password}}"
  loop: "{{ domain.users }}"
  ignore_errors: yes